- name: configuring backend
  hosts: backend
  become: yes
  tasks:
    - name: Disabling node js
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enabling nodejs 20 version
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: installed

    - name: adding the expense user
      ansible.builtin.user:
        name: expense
        state: present

    - name: creating an app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: 