- name: configuring frontend
  hosts: web
  become: yes
  tasks:
  - name: install nginx 
    ansible.builtin.package:
      name: nginx
      state: installed
      enabled: yes

  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started