- name: configuring frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx 
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove the default content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: download the frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip