- name: creating mysql server
  hosts: mysql
  become: yes
  vars:
    login_password: "ExpenseApp@1"
    login_host: "mysql.reyanshsai.online"
  tasks:
    - name: installing mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: installed
    
    - name: starting mysql - server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: logging through root password before setting up
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ login_password }}"
        login_host: "{{ login_host }}"
      ignore_errors: true
      register: mysql_info

    - name: printing mysql information
      ansible.builtin.debug:
        msg: {{ mysql_info }}
